# testing using CircleCI orb
# see https://on.cypress.io/circleci-orb

# for non-orb configuration see old commit
# https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml

# to use CircleCI orbs need to use version >= 2.1
version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.3.0

jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/

workflows:
  build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          # and builds the app using this command
          build: "npm run build"

      # runs on 1 machines
      - cypress/run:
          # name this job because we are running "cypress/run" several times
          # with different parameters
          name: "1 machine"
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - cypress/install
          group: "1x-electron" # name this group
          start: "npm run serve" # start server before running tests

      # run on 1 machines using Chrome browser
      - cypress/run:
          name: "1 machine using Chrome"
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - cypress/install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome69
          # use browser "chrome" for running tests
          browser: chrome
          group: "1x-chrome"
          start: "npm run serve"
